#!/bin/sh

bspc monitor eDP1 -d I II III IV V
bspc monitor DP1 -d VI VII 
bspc monitor HDMI3 -d VIII IX X

bspc config border_width         4
bspc config active_border_color \#ECEFF4
bspc config normal_border_color \#3B4252
bspc config window_gap          12

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle	  false
bspc config focus_follows_pointer true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar:thunar state=floating
bspc rule -a Nightly state=tiled

bspc rule -a Nightly:Browser state=floating
bspc rule -a Nightly:Dialog state=floating
bspc rule -a Nightly:firefox state=floating
bspc rule -a Nightly:Prompt state=floating

compton --unredir-if-possible --config ~/.config/compton.conf &
~/.fehbg &
$HOME/.config/polybar/launch.sh &
