#!/bin/sh

bspc monitor -d I II III IV V
bspc monitor DP1 -d VI VII VIII IX
bspc monitor HDMI3 -d X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle	  false
bspc config focus_follows_pointer true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar:thunar state=floating

compton --unredir-if-possible &
~/.fehbg &
$HOME/.config/polybar/launch.sh &
