#!/bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config focus_follows_pointer true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar:thunar state=floating
